//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAccessLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int productid { get; set; }
        public string categoryid { get; set; }
        public string productname { get; set; }
        public Nullable<int> price { get; set; }
        public string description { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
